sudo: required

language: generic

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7

services:
  - docker

install:
  - ./test/travis-ci/install.sh

script:
  - ./test/travis-ci/run_test.sh --docker-image=amplab/ray:test-base 'source setup-env.sh && cd test && python runtest.py'
